# numpy
NumPy is the fundamental library for the numerical computation. It is an integral 
part of the Scientific Python Ecosystem.

In [1]:
import numpy as np

In [3]:
 #simple Ndarray as follows:
lst1 = [1, 2, 3]
arr1 = np.array(lst1)
arr1

array([1, 2, 3])

In [4]:
#multidimensional arrays as follows:
arr1 = np.array([[1, 2, 3], [4, 5, 6]], np.int16)
arr1


array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)

In [8]:
# 3d arrays
arr1 = np.array([[[1, 2, 3], [4, 5, 6]],
 [[7, 8, 9], [0, 0, 0]],
 [[-1, -1, -1], [1, 1, 1]]], np.int16)
print(arr1 [0, 0, 0])
print(arr1 [1, 1, 2])
print(arr1 [:, 1, 1])
print(arr1.ndim)
print(arr1.shape)
# compute the transpose
print(arr1.T)

1
0
[5 0 1]
3
(3, 2, 3)
[[[ 1  7 -1]
  [ 4  0  1]]

 [[ 2  8 -1]
  [ 5  0  1]]

 [[ 3  9 -1]
  [ 6  0  1]]]


 NumPy Constants
 NumPy library has many useful mathematical and scientific constants we can use in programs. The following code snippet prints all such important constants

In [9]:
 print(np.inf)
 print(np.NAN)
 print(np.NINF)
 print(np.NZERO)
 print(np.PZERO)
 print(np.e)
 print(np.euler_gamma)
 print(np.pi)

inf
nan
-inf
-0.0
0.0
2.718281828459045
0.5772156649015329
3.141592653589793
